=== sachanta/validateDetectRules/AppDynamicsREST/examples/xsd/backend_metrics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="BackendResponseTimes" type="BackendResponseTimesType"/>
    <xs:complexType name="BackendResponseTimesType">
        <xs:sequence>
            <xs:element type="BackendType" name="Backend" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="Controller"/>
        <xs:attribute type="xs:dateTime" name="GenerationTime"/>
    </xs:complexType>
    <xs:simpleType name="empty">
        <xs:restriction base="xs:string">
            <xs:length value="0" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="isoDate">
        <xs:union memberTypes="xs:dateTime empty" />
    </xs:simpleType>
    <xs:complexType name="BackendType">
        <xs:sequence>
            <xs:element type="xs:string" name="ApplicationName"/>
            <xs:element type="xs:string" name="BackendName"/>
            <xs:element type="xs:long" name="AverageResponseTime"/>
            <xs:element type="xs:long" name="CallsPerMinute"/>
            <xs:element type="xs:long" name="TotalCalls"/>
            <xs:element type="xs:long" name="MaximumCallsPerMinute"/>
            <xs:element type="isoDate" name="MaximumCallTime"/>
            <xs:element type="xs:long" name="ErrorsPerMinute"/>
            <xs:element type="xs:long" name="TotalErrors"/>
            <xs:element type="xs:long" name="MaximumErrorsPerMinute"/>
            <xs:element type="isoDate" nillable="true" name="MaximumErrorTime"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== sachanta/validateDetectRules/AppDynamicsREST/data/backend_metrics.xml
<?xml version="1.0" encoding="UTF-8"?>
<BackendResponseTimes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Controller="http://localhost:8080/controller/rest" GenerationTime="2013-06-14T21:50:41.100883-04:00" xsi:noNamespaceSchemaLocation="../examples/xsd/backend_metrics.xsd">
  <Backend>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BackendName>Discovered backend call - APPDY-MySQL DB-LOCALHOST</BackendName>
    <AverageResponseTime>0</AverageResponseTime>
    <CallsPerMinute>0</CallsPerMinute>
    <TotalCalls>0</TotalCalls>
    <MaximumCallsPerMinute>0</MaximumCallsPerMinute>
    <MaximumCallTime></MaximumCallTime>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <TotalErrors>0</TotalErrors>
    <MaximumErrorsPerMinute>0</MaximumErrorsPerMinute>
    <MaximumErrorTime></MaximumErrorTime>
  </Backend>
  <Backend>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BackendName>Discovered backend call - Active MQ-OrderQueue</BackendName>
    <AverageResponseTime>0</AverageResponseTime>
    <CallsPerMinute>0</CallsPerMinute>
    <TotalCalls>0</TotalCalls>
    <MaximumCallsPerMinute>0</MaximumCallsPerMinute>
    <MaximumCallTime></MaximumCallTime>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <TotalErrors>0</TotalErrors>
    <MaximumErrorsPerMinute>0</MaximumErrorsPerMinute>
    <MaximumErrorTime></MaximumErrorTime>
  </Backend>
  <Backend>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BackendName>Discovered backend call - INVENTORY-MySQL DB-LOCALHOST</BackendName>
    <AverageResponseTime>0</AverageResponseTime>
    <CallsPerMinute>0</CallsPerMinute>
    <TotalCalls>0</TotalCalls>
    <MaximumCallsPerMinute>0</MaximumCallsPerMinute>
    <MaximumCallTime></MaximumCallTime>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <TotalErrors>0</TotalErrors>
    <MaximumErrorsPerMinute>0</MaximumErrorsPerMinute>
    <MaximumErrorTime></MaximumErrorTime>
  </Backend>
  <Backend>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BackendName>Discovered backend call - Oracle - 10.0.0</BackendName>
    <AverageResponseTime>0</AverageResponseTime>
    <CallsPerMinute>0</CallsPerMinute>
    <TotalCalls>0</TotalCalls>
    <MaximumCallsPerMinute>0</MaximumCallsPerMinute>
    <MaximumCallTime></MaximumCallTime>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <TotalErrors>0</TotalErrors>
    <MaximumErrorsPerMinute>0</MaximumErrorsPerMinute>
    <MaximumErrorTime></MaximumErrorTime>
  </Backend>
  <Backend>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BackendName>Inventory Server</BackendName>
    <AverageResponseTime>0</AverageResponseTime>
    <CallsPerMinute>0</CallsPerMinute>
    <TotalCalls>0</TotalCalls>
    <MaximumCallsPerMinute>0</MaximumCallsPerMinute>
    <MaximumCallTime></MaximumCallTime>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <TotalErrors>0</TotalErrors>
    <MaximumErrorsPerMinute>0</MaximumErrorsPerMinute>
    <MaximumErrorTime></MaximumErrorTime>
  </Backend>
</BackendResponseTimes>
