=== sachanta/validateDetectRules/AppDynamicsREST/examples/xsd/bt_metrics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="BusinessTransactions" type="BusinessTransactionsType"/>
  <xs:complexType name="BusinessTransactionsType">
    <xs:sequence>
      <xs:element type="BusinessTransactionType" name="BusinessTransaction" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:anyURI" name="Controller"/>
    <xs:attribute type="xs:dateTime" name="GenerationTime"/>
  </xs:complexType>
  <xs:complexType name="BusinessTransactionType">
    <xs:sequence>
      <xs:element type="xs:string" name="ApplicationName"/>
      <xs:element type="xs:string" name="BusinessTransactionName"/>
      <xs:element type="xs:string" name="TierName"/>
      <xs:element type="xs:long" name="AverageResponseTime"/>
      <xs:element type="xs:long" name="CallsPerMinute"/>
      <xs:element type="xs:long" name="TotalCalls"/>
      <xs:element type="xs:long" name="TotalErrors" />
      <xs:element type="xs:long" name="ErrorsPerMinute"/>
      <xs:element type="xs:float" name="ErrorPercentage"/>
      <xs:element type="xs:long" name="SlowCalls" />
      <xs:element type="xs:long" name="VerySlowCalls" />
      <xs:element type="xs:long" name="Stalls" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== sachanta/validateDetectRules/AppDynamicsREST/data/bt_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<BusinessTransactions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Controller="http://localhost:8080/controller/rest" GenerationTime="2013-06-14T21:54:58.701673-04:00" xsi:noNamespaceSchemaLocation="../examples/xsd/bt_metrics.xsd">
  <BusinessTransaction>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BusinessTransactionName>/appdynamicspilot/</BusinessTransactionName>
    <TierName>ECommerce Server</TierName>
    <AverageResponseTime>23</AverageResponseTime>
    <CallsPerMinute>50</CallsPerMinute>
    <TotalCalls>750</TotalCalls>
    <TotalErrors>0</TotalErrors>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <ErrorPercentage>0.0</ErrorPercentage>
    <SlowCalls>0</SlowCalls>
    <VerySlowCalls>0</VerySlowCalls>
    <Stalls>0</Stalls>
  </BusinessTransaction>
  <BusinessTransaction>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BusinessTransactionName>UserLogOut.memberLogOut</BusinessTransactionName>
    <TierName>ECommerce Server</TierName>
    <AverageResponseTime>8</AverageResponseTime>
    <CallsPerMinute>74</CallsPerMinute>
    <TotalCalls>1110</TotalCalls>
    <TotalErrors>0</TotalErrors>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <ErrorPercentage>0.0</ErrorPercentage>
    <SlowCalls>0</SlowCalls>
    <VerySlowCalls>0</VerySlowCalls>
    <Stalls>0</Stalls>
  </BusinessTransaction>
  <BusinessTransaction>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BusinessTransactionName>UserLogin.memberLogin</BusinessTransactionName>
    <TierName>ECommerce Server</TierName>
    <AverageResponseTime>14</AverageResponseTime>
    <CallsPerMinute>50</CallsPerMinute>
    <TotalCalls>750</TotalCalls>
    <TotalErrors>0</TotalErrors>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <ErrorPercentage>0.0</ErrorPercentage>
    <SlowCalls>0</SlowCalls>
    <VerySlowCalls>0</VerySlowCalls>
    <Stalls>0</Stalls>
  </BusinessTransaction>
  <BusinessTransaction>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BusinessTransactionName>ViewCart.addToCart</BusinessTransactionName>
    <TierName>ECommerce Server</TierName>
    <AverageResponseTime>23</AverageResponseTime>
    <CallsPerMinute>50</CallsPerMinute>
    <TotalCalls>750</TotalCalls>
    <TotalErrors>0</TotalErrors>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <ErrorPercentage>0.0</ErrorPercentage>
    <SlowCalls>0</SlowCalls>
    <VerySlowCalls>0</VerySlowCalls>
    <Stalls>0</Stalls>
  </BusinessTransaction>
  <BusinessTransaction>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BusinessTransactionName>ViewCart.sendItems</BusinessTransactionName>
    <TierName>ECommerce Server</TierName>
    <AverageResponseTime>487</AverageResponseTime>
    <CallsPerMinute>74</CallsPerMinute>
    <TotalCalls>1110</TotalCalls>
    <TotalErrors>30</TotalErrors>
    <ErrorsPerMinute>2</ErrorsPerMinute>
    <ErrorPercentage>2.7</ErrorPercentage>
    <SlowCalls>0</SlowCalls>
    <VerySlowCalls>1</VerySlowCalls>
    <Stalls>0</Stalls>
  </BusinessTransaction>
  <BusinessTransaction>
    <ApplicationName>ACME Book Store Application</ApplicationName>
    <BusinessTransactionName>ViewItems.getAllItems</BusinessTransactionName>
    <TierName>ECommerce Server</TierName>
    <AverageResponseTime>23</AverageResponseTime>
    <CallsPerMinute>50</CallsPerMinute>
    <TotalCalls>750</TotalCalls>
    <TotalErrors>0</TotalErrors>
    <ErrorsPerMinute>0</ErrorsPerMinute>
    <ErrorPercentage>0.0</ErrorPercentage>
    <SlowCalls>0</SlowCalls>
    <VerySlowCalls>0</VerySlowCalls>
    <Stalls>0</Stalls>
  </BusinessTransaction>
</BusinessTransactions>
